version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - performance
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - performance
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

# Descomente essa parte quando tiver criado a imagem local.

#  reactive:
#    image: reactive:1.0
#    ports:
#      - 8090:8080
#    networks:
#      - performance
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 768M
#        reservations:
#          cpus: '1.0'
#          memory: 768M
#    depends_on:
#      - mongo
#
#  courotine:
#    image: coroutine:1.0
#    ports:
#      - 8091:8080
#    networks:
#      - performance
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 768M
#        reservations:
#          cpus: '1.0'
#          memory: 768M
#    depends_on:
#      - mongo
#
#  reactive-mvc:
#    image: reactive-mvc:1.0
#    ports:
#      - 8092:8080
#    networks:
#      - performance
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 768M
#        reservations:
#          cpus: '1.0'
#          memory: 768M
#    depends_on:
#      - mongo
#
#  imperative:
#    image: imperative:1.0
#    ports:
#      - 8093:8080
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 768M
#        reservations:
#          cpus: '1.0'
#          memory: 768M
#    networks:
#      - performance
#    depends_on:
#      - mongo

networks:
  performance:
    driver: bridge